import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/main-nav";
import { Footer } from "@/components/footer";
import { ReactQueryWrapper } from "@/components/react-query-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <ReactQueryWrapper>
          <NavigationBar />
          {children}
          <Footer />
        </ReactQueryWrapper>
      </body>
    </html >
  );
}
